// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD13EGuZwK80Nl948xC8TgiqN4FF1pbi-E',
    appId: '1:310674472470:web:a8c4cc8309c5c4f2de3f37',
    messagingSenderId: '310674472470',
    projectId: 'damh-ltdd',
    authDomain: 'damh-ltdd.firebaseapp.com',
    storageBucket: 'damh-ltdd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqb57-SRndFr5xPY1r8rNyLyUCbyWxuxU',
    appId: '1:310674472470:android:1ae0aff9926e0a12de3f37',
    messagingSenderId: '310674472470',
    projectId: 'damh-ltdd',
    storageBucket: 'damh-ltdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvLCIMp6paeGFHsoumxuQBSurstmhkUTo',
    appId: '1:310674472470:ios:f29516181156a1edde3f37',
    messagingSenderId: '310674472470',
    projectId: 'damh-ltdd',
    storageBucket: 'damh-ltdd.firebasestorage.app',
    iosBundleId: 'com.example.appshopbanthucung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvLCIMp6paeGFHsoumxuQBSurstmhkUTo',
    appId: '1:310674472470:ios:f29516181156a1edde3f37',
    messagingSenderId: '310674472470',
    projectId: 'damh-ltdd',
    storageBucket: 'damh-ltdd.firebasestorage.app',
    iosBundleId: 'com.example.appshopbanthucung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD13EGuZwK80Nl948xC8TgiqN4FF1pbi-E',
    appId: '1:310674472470:web:a8c4cc8309c5c4f2de3f37',
    messagingSenderId: '310674472470',
    projectId: 'damh-ltdd',
    authDomain: 'damh-ltdd.firebaseapp.com',
    storageBucket: 'damh-ltdd.firebasestorage.app',
  );
}
